# Etapa 1: Construcción
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["EntregableAndres/EntregableAndres.csproj", "EntregableAndres/"]
RUN dotnet restore "EntregableAndres/EntregableAndres.csproj"
COPY . .
WORKDIR "/src/EntregableAndres"
RUN dotnet build "EntregableAndres.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "EntregableAndres.csproj" -c Release -o /app/publish

# Etapa 2: Runtime
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "EntregableAndres.dll"]